openapi: 3.1.0

info:
  title: SonnenBatterie API
  version: ${VERSION}
  contact:
    name: Lars Michaelis
    email: mail@larmic.de
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

paths:
  /sonnen-api/api/system:
    get:
      summary: Returns SonnenBatterie info.
      responses:
        '200':
          description: SonnenBatterie system
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/System"
        '404':
          description: SonnenBatterie not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProtocolError"
  /sonnen-api/api/consumption:
    get:
      summary: Returns SonnenBatterie consumption info.
      responses:
        '200':
          description: SonnenBatterie consumption info
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Consumption"
        '404':
          description: SonnenBatterie not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProtocolError"
  /sonnen-api/api/status:
    get:
      summary: Returns SonnenBatterie generation info.
      responses:
        '200':
          description: SonnenBatterie generation info
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Generation"
        '404':
          description: SonnenBatterie not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProtocolError"


components:
  schemas:
    System:
      required:
        - ip
        - wanIp
        - vpnIp
        - model
        - mac
        - softwareVersion
        - hardwareVersion
        - led
      properties:
        ip:
          type: string
          description: SonnenBatterie internal addres (i.e. 10.0.0.100).
        wanIp:
          type: string
          description: SonnenBatterie external addres (i.e. 31.31.31.31).
        vpnIp:
          type: string
          description: SonnenBatterie vpn addres (i.e. 41.41.41.41).
        model:
          type: string
          description: SonnenBatterie model name.
        mac:
          type: string
          description: SonnenBatterie mac address.
        softwareVersion:
          type: string
          description: SonnenBatterie software version.
        hardwareVersion:
          type: string
          description: SonnenBatterie hardware version.
        led:
          type: string
          description: SonnenBatterie led state.
          enum:
            - white
            - green
            - orange
            - red

    Consumption:
      required:
        - current_mw
      properties:
        current_mw:
          type: integer
          description: Actual house consumption in milli watt

    Status:
      required:
        - grid_feed_in_mw
        - production_mw
        - charge_level
        - charge_mode
      properties:
        grid_feed_in_mw:
          type: integer
          description: Actual grid feed in in milli watt
        production_mw:
          type: integer
          description: Actual solar production in milli watt
        charge_level:
          type: integer
          description: Actual battery charge level in percent
        charge_mode:
          type: string
          description: SonnenBatterie charge mode.
          enum:
            - charging
            - discharging
            - idle

    ProtocolError:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: HTTP code.
        message:
          type: string
          description: Error message.
