GET http://10.0.40.100/api/v2/latestdata
Accept: application/json
Auth-Token: FNGekXwK5Mckv-IIpLSImEejxTqHHaZlfRBB2BwCP7yEjSNV-7TkGffKn8G-YeCQRJtRbBvZ3Q-opZ9QYCBC8gOu-GxzYcaDjA5_jqOluH_hW7zhXeEMfvqlhl4UMKruYhlqQ9ME2TsO3ZWGwRSLSBM480p-0s-kSXauKNH6y6P2CZg8cUQROP1xw5nNtvgQKabQqPzAS_lpqX0cXifk6TlpvvAgCbxkWaU7gYL6ROcvg3mMeFX55nRVzdauNn9h70MMZUHYFIb-VIWEdvSwdxVmscTwtizn5D4u2BzXHRbe-jp7QCtokyPbP-qgsKR-5yv9JOILUcnga99oKc4zt8Aoku5WsI7xINY09Tld3dBOw1xGcOanoBIGtht-zhzf1ET7z71zpH5aW06glfJbXdHM7qinjar58btSqAcyMYOjMrHf_dMfGGWVN4Hn10_1ZBTTcxgnBiAOqTwBuPT61osPZhDYt-OaDlzKcVTGcoiyAPJdDu9gte7iUFclg8IUN1-lCTvGiJDyggM2M3FjdRTHgzFRp4Oe5w3lgK5YNHxngvQFMIxLuAf4urH_QcywJTWRZH84zOzoNasU-jkepFWdpePa0APq2wsKlnLq--QvxrI3mNyImcZQWsBgLFFaIaXkMHLmlz--sQWdP3Li93AXG2L6PKyXMyKeHKbXF0g
###

GET http://10.0.40.100/api/v2/battery
Accept: application/json
Auth-Token: FNGekXwK5Mckv-IIpLSImEejxTqHHaZlfRBB2BwCP7yEjSNV-7TkGffKn8G-YeCQRJtRbBvZ3Q-opZ9QYCBC8gOu-GxzYcaDjA5_jqOluH_hW7zhXeEMfvqlhl4UMKruYhlqQ9ME2TsO3ZWGwRSLSBM480p-0s-kSXauKNH6y6P2CZg8cUQROP1xw5nNtvgQKabQqPzAS_lpqX0cXifk6TlpvvAgCbxkWaU7gYL6ROcvg3mMeFX55nRVzdauNn9h70MMZUHYFIb-VIWEdvSwdxVmscTwtizn5D4u2BzXHRbe-jp7QCtokyPbP-qgsKR-5yv9JOILUcnga99oKc4zt8Aoku5WsI7xINY09Tld3dBOw1xGcOanoBIGtht-zhzf1ET7z71zpH5aW06glfJbXdHM7qinjar58btSqAcyMYOjMrHf_dMfGGWVN4Hn10_1ZBTTcxgnBiAOqTwBuPT61osPZhDYt-OaDlzKcVTGcoiyAPJdDu9gte7iUFclg8IUN1-lCTvGiJDyggM2M3FjdRTHgzFRp4Oe5w3lgK5YNHxngvQFMIxLuAf4urH_QcywJTWRZH84zOzoNasU-jkepFWdpePa0APq2wsKlnLq--QvxrI3mNyImcZQWsBgLFFaIaXkMHLmlz--sQWdP3Li93AXG2L6PKyXMyKeHKbXF0g
###

GET http://10.0.40.100/api/v2/configurations
Accept: application/json
Auth-Token: FNGekXwK5Mckv-IIpLSImEejxTqHHaZlfRBB2BwCP7yEjSNV-7TkGffKn8G-YeCQRJtRbBvZ3Q-opZ9QYCBC8gOu-GxzYcaDjA5_jqOluH_hW7zhXeEMfvqlhl4UMKruYhlqQ9ME2TsO3ZWGwRSLSBM480p-0s-kSXauKNH6y6P2CZg8cUQROP1xw5nNtvgQKabQqPzAS_lpqX0cXifk6TlpvvAgCbxkWaU7gYL6ROcvg3mMeFX55nRVzdauNn9h70MMZUHYFIb-VIWEdvSwdxVmscTwtizn5D4u2BzXHRbe-jp7QCtokyPbP-qgsKR-5yv9JOILUcnga99oKc4zt8Aoku5WsI7xINY09Tld3dBOw1xGcOanoBIGtht-zhzf1ET7z71zpH5aW06glfJbXdHM7qinjar58btSqAcyMYOjMrHf_dMfGGWVN4Hn10_1ZBTTcxgnBiAOqTwBuPT61osPZhDYt-OaDlzKcVTGcoiyAPJdDu9gte7iUFclg8IUN1-lCTvGiJDyggM2M3FjdRTHgzFRp4Oe5w3lgK5YNHxngvQFMIxLuAf4urH_QcywJTWRZH84zOzoNasU-jkepFWdpePa0APq2wsKlnLq--QvxrI3mNyImcZQWsBgLFFaIaXkMHLmlz--sQWdP3Li93AXG2L6PKyXMyKeHKbXF0g
###

GET http://10.0.40.100/api/v2/powermeter
Accept: application/json
Auth-Token: FNGekXwK5Mckv-IIpLSImEejxTqHHaZlfRBB2BwCP7yEjSNV-7TkGffKn8G-YeCQRJtRbBvZ3Q-opZ9QYCBC8gOu-GxzYcaDjA5_jqOluH_hW7zhXeEMfvqlhl4UMKruYhlqQ9ME2TsO3ZWGwRSLSBM480p-0s-kSXauKNH6y6P2CZg8cUQROP1xw5nNtvgQKabQqPzAS_lpqX0cXifk6TlpvvAgCbxkWaU7gYL6ROcvg3mMeFX55nRVzdauNn9h70MMZUHYFIb-VIWEdvSwdxVmscTwtizn5D4u2BzXHRbe-jp7QCtokyPbP-qgsKR-5yv9JOILUcnga99oKc4zt8Aoku5WsI7xINY09Tld3dBOw1xGcOanoBIGtht-zhzf1ET7z71zpH5aW06glfJbXdHM7qinjar58btSqAcyMYOjMrHf_dMfGGWVN4Hn10_1ZBTTcxgnBiAOqTwBuPT61osPZhDYt-OaDlzKcVTGcoiyAPJdDu9gte7iUFclg8IUN1-lCTvGiJDyggM2M3FjdRTHgzFRp4Oe5w3lgK5YNHxngvQFMIxLuAf4urH_QcywJTWRZH84zOzoNasU-jkepFWdpePa0APq2wsKlnLq--QvxrI3mNyImcZQWsBgLFFaIaXkMHLmlz--sQWdP3Li93AXG2L6PKyXMyKeHKbXF0g
###

GET http://10.0.40.100/api/v2/inverter
Accept: application/json
Auth-Token: FNGekXwK5Mckv-IIpLSImEejxTqHHaZlfRBB2BwCP7yEjSNV-7TkGffKn8G-YeCQRJtRbBvZ3Q-opZ9QYCBC8gOu-GxzYcaDjA5_jqOluH_hW7zhXeEMfvqlhl4UMKruYhlqQ9ME2TsO3ZWGwRSLSBM480p-0s-kSXauKNH6y6P2CZg8cUQROP1xw5nNtvgQKabQqPzAS_lpqX0cXifk6TlpvvAgCbxkWaU7gYL6ROcvg3mMeFX55nRVzdauNn9h70MMZUHYFIb-VIWEdvSwdxVmscTwtizn5D4u2BzXHRbe-jp7QCtokyPbP-qgsKR-5yv9JOILUcnga99oKc4zt8Aoku5WsI7xINY09Tld3dBOw1xGcOanoBIGtht-zhzf1ET7z71zpH5aW06glfJbXdHM7qinjar58btSqAcyMYOjMrHf_dMfGGWVN4Hn10_1ZBTTcxgnBiAOqTwBuPT61osPZhDYt-OaDlzKcVTGcoiyAPJdDu9gte7iUFclg8IUN1-lCTvGiJDyggM2M3FjdRTHgzFRp4Oe5w3lgK5YNHxngvQFMIxLuAf4urH_QcywJTWRZH84zOzoNasU-jkepFWdpePa0APq2wsKlnLq--QvxrI3mNyImcZQWsBgLFFaIaXkMHLmlz--sQWdP3Li93AXG2L6PKyXMyKeHKbXF0g
###

GET http://10.0.40.100/api/v1/status/
Accept: application/json
Auth-Token: FNGekXwK5Mckv-IIpLSImEejxTqHHaZlfRBB2BwCP7yEjSNV-7TkGffKn8G-YeCQRJtRbBvZ3Q-opZ9QYCBC8gOu-GxzYcaDjA5_jqOluH_hW7zhXeEMfvqlhl4UMKruYhlqQ9ME2TsO3ZWGwRSLSBM480p-0s-kSXauKNH6y6P2CZg8cUQROP1xw5nNtvgQKabQqPzAS_lpqX0cXifk6TlpvvAgCbxkWaU7gYL6ROcvg3mMeFX55nRVzdauNn9h70MMZUHYFIb-VIWEdvSwdxVmscTwtizn5D4u2BzXHRbe-jp7QCtokyPbP-qgsKR-5yv9JOILUcnga99oKc4zt8Aoku5WsI7xINY09Tld3dBOw1xGcOanoBIGtht-zhzf1ET7z71zpH5aW06glfJbXdHM7qinjar58btSqAcyMYOjMrHf_dMfGGWVN4Hn10_1ZBTTcxgnBiAOqTwBuPT61osPZhDYt-OaDlzKcVTGcoiyAPJdDu9gte7iUFclg8IUN1-lCTvGiJDyggM2M3FjdRTHgzFRp4Oe5w3lgK5YNHxngvQFMIxLuAf4urH_QcywJTWRZH84zOzoNasU-jkepFWdpePa0APq2wsKlnLq--QvxrI3mNyImcZQWsBgLFFaIaXkMHLmlz--sQWdP3Li93AXG2L6PKyXMyKeHKbXF0g
###

GET http://10.0.40.100/api/v1/battery-systems/c2670432-311e-42be-a42b-115bb08a6297/electric-units
Accept: application/json
Auth-Token: FNGekXwK5Mckv-IIpLSImEejxTqHHaZlfRBB2BwCP7yEjSNV-7TkGffKn8G-YeCQRJtRbBvZ3Q-opZ9QYCBC8gOu-GxzYcaDjA5_jqOluH_hW7zhXeEMfvqlhl4UMKruYhlqQ9ME2TsO3ZWGwRSLSBM480p-0s-kSXauKNH6y6P2CZg8cUQROP1xw5nNtvgQKabQqPzAS_lpqX0cXifk6TlpvvAgCbxkWaU7gYL6ROcvg3mMeFX55nRVzdauNn9h70MMZUHYFIb-VIWEdvSwdxVmscTwtizn5D4u2BzXHRbe-jp7QCtokyPbP-qgsKR-5yv9JOILUcnga99oKc4zt8Aoku5WsI7xINY09Tld3dBOw1xGcOanoBIGtht-zhzf1ET7z71zpH5aW06glfJbXdHM7qinjar58btSqAcyMYOjMrHf_dMfGGWVN4Hn10_1ZBTTcxgnBiAOqTwBuPT61osPZhDYt-OaDlzKcVTGcoiyAPJdDu9gte7iUFclg8IUN1-lCTvGiJDyggM2M3FjdRTHgzFRp4Oe5w3lgK5YNHxngvQFMIxLuAf4urH_QcywJTWRZH84zOzoNasU-jkepFWdpePa0APq2wsKlnLq--QvxrI3mNyImcZQWsBgLFFaIaXkMHLmlz--sQWdP3Li93AXG2L6PKyXMyKeHKbXF0g
###

GET http://10.0.40.100/api/v1/chargers/653b8f7d-05e2-4744-ab71-e7ac404029fa/live-state
Accept: application/json
Auth-Token: FNGekXwK5Mckv-IIpLSImEejxTqHHaZlfRBB2BwCP7yEjSNV-7TkGffKn8G-YeCQRJtRbBvZ3Q-opZ9QYCBC8gOu-GxzYcaDjA5_jqOluH_hW7zhXeEMfvqlhl4UMKruYhlqQ9ME2TsO3ZWGwRSLSBM480p-0s-kSXauKNH6y6P2CZg8cUQROP1xw5nNtvgQKabQqPzAS_lpqX0cXifk6TlpvvAgCbxkWaU7gYL6ROcvg3mMeFX55nRVzdauNn9h70MMZUHYFIb-VIWEdvSwdxVmscTwtizn5D4u2BzXHRbe-jp7QCtokyPbP-qgsKR-5yv9JOILUcnga99oKc4zt8Aoku5WsI7xINY09Tld3dBOw1xGcOanoBIGtht-zhzf1ET7z71zpH5aW06glfJbXdHM7qinjar58btSqAcyMYOjMrHf_dMfGGWVN4Hn10_1ZBTTcxgnBiAOqTwBuPT61osPZhDYt-OaDlzKcVTGcoiyAPJdDu9gte7iUFclg8IUN1-lCTvGiJDyggM2M3FjdRTHgzFRp4Oe5w3lgK5YNHxngvQFMIxLuAf4urH_QcywJTWRZH84zOzoNasU-jkepFWdpePa0APq2wsKlnLq--QvxrI3mNyImcZQWsBgLFFaIaXkMHLmlz--sQWdP3Li93AXG2L6PKyXMyKeHKbXF0g
###

GET https://my-api.sonnen.de/v1/battery-systems/c2670432-311e-42be-a42b-115bb08a6297/electric-units?page[limit]=10&page[number]=1
authorization: Bearer Arjbqdjcg9HZxnTiBgdmapBYprVJKre8f2kXlb7mDyE
###

GET https://my-api.sonnen.de/v1/chargers/653b8f7d-05e2-4744-ab71-e7ac404029fa/live-state
authorization: Bearer Arjbqdjcg9HZxnTiBgdmapBYprVJKre8f2kXlb7mDyE
###

GET https://my-api.sonnen.de/v1/chargers/
authorization: Bearer Arjbqdjcg9HZxnTiBgdmapBYprVJKre8f2kXlb7mDyE
###


# https://my-api.sonnen.de/v1/battery-systems/c2670432-311e-42be-a42b-115bb08a6297/electric-units?page[limit]=10&page[number]=1
# https://my-api.sonnen.de/v1/battery-systems/c2670432-311e-42be-a42b-115bb08a6297/electric-units?page[limit]=10&page[number]=1